### ISSUE TITLE
Corrigir UPDATE e exceção ao consultar cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [caionmarqz/dsclientes#1]
Olá Caio, tudo bem?
Meu nome é Alexandre e estou corrigindo sua atividade!

Infelizmente seu trabalho não foi aceito! Mas fique tranquilo, basta fazer os ajustes e enviá-lo novamente. Seguem abaixo as adequações necessárias:

- Ao atualizar (ex: passando o id=1), a sua api ao invés de atualizar o cliente de id=1 está inserindo um novo cliente. Pelo que eu vi no seu código, você vai precisar alterar o seu service. Antes de chamar o save do repository, você deve executar um método para copiar os dados do DTO para a sua entitdade.

- Outra alteração necessária é o tratamento de exceções. Ao **consultar** um cliente com id inexistente retorna um erro **500**.

Por favor, assim que puder faça os ajustes e envie sua atividade novamente para que eu possa revisá-la.

Abraço e bons estudos

**Comment by oliveiralex** [comment]
Olá Caio,

Acabei de corrigir a sua atividade! A correção para o tratamento de exceção está funcionando certinho! Parabéns!
Porém, ainda está com um problema no momento da atualização do cliente. Vou descrever o seguinte teste que eu fiz e peço que você o faça também para verificar.

1. Executei a aplicação pela primeira vez
2. Lá no Postman eu executei o **delete** client, deletando o usuário de id = 1;
3. Em seguida eu executei o **update** client, alterando o usuário de id = 1;

Neste caso, o esperado é que fosse retornado uma exceção do tipo _ResourceNotFound_, porém ao executar o update está inserindo um novo cliente. Perceba que o id do cliente vai ser incrementado. 

Para fazer a correção, você terá que seguir os seguintes passos no seu update:

1. Instancia o cliente usando o getOne
2. Copia os dados do DTO para a entidade. Perceba que no projeto do dscatalog o Nélio usou um método auxiliar.
3. Executa o save novamente.

Desta forma, vou validar a sua atividade, mas peço que você faça os reparos e qualquer dúvida estou à disposição.

Abraço

**Comment by caionmarqz** [comment]
Vou ver, obrigado.
